**1. What does Pandas stand for?**
*An open source Python package.*

**2. What are the 2 collections used in Pandas?**
*Panel Data*
*Python Data Analysis*

**3. Name 4 things Pandas can do for us.**
*Data Cleansing,*
*Data normalization,*
*Data visualization,*
*Data inspection*

**4. To permanently sort a DataFrame, which keyword should one use with the df.sort() method?**
*True*

**5. What is a CSV?**
*Comma Seperated Value file*

**6. When cleaning data what values do we not like in our data?**
*blank or null fields*

In [48]:
#Coding Exercise
#Question 7

import numpy as np

a = np.array([[1,2,3],
             [7,8,9]])
#print(a)

#reshaped above array
c = a.reshape(1,3,2)
print(c)



[[[1 2]
  [3 7]
  [8 9]]]


In [27]:
#Coding Exercise
#Question 8

import numpy as np

#create an array with 6 linearly spaced values between 0 and 20, use .linspace
c = np.linspace(0, 20, num=6)
print(c)


[ 0.  4.  8. 12. 16. 20.]


In [34]:
#Coding Exercise
#Question 9
import copy

#above array
c = np.array(range(0, 21))
print(c)

#Deep copy of above array
d = copy.deepcopy(c)
print(d)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [51]:
#Coding Exercise
#Question 10
import numpy as np

#concatenate these 3 arrays
a = ([[25, 16]])
b = ([[11, 2], [13, 4]])
c = ([[7, 81], [5, 6], [11, 12]])


#concatenated the above arrays
newArray = np.concatenate((a,b,c),axis=0)
print(newArray)


[[25 16]
 [11  2]
 [13  4]
 [ 7 81]
 [ 5  6]
 [11 12]]


In [52]:
#Coding Exercise
#Question 11

# Sort newArray in order into sortedArray

sortArray = np.sort(newArray)
print(sortArray)

[[16 25]
 [ 2 11]
 [ 4 13]
 [ 7 81]
 [ 5  6]
 [11 12]]


In [59]:
#Coding Exercise
#Question 12
# Unpack the array tuples from the above 'reshapedArray' into 4 well named variables. Print the 4 variables.
new = sortArray.reshape(4,3)
#print(new)

#unpacked into 4 variables
l,m,n,o = new



print("Tuple 1", l)
print("Tupl 2", m)
print("Tuple 3", n)
print("Tuple 4", o)




Tuple 1 [16 25  2]
Tupl 2 [11  4 13]
Tuple 3 [ 7 81  5]
Tuple 4 [ 6 11 12]


In [16]:
#Coding Exercise
#Question 13
import numpy as np

one = ([10, 11, 12, 13, 14, 15, 16, 17])
two = ([20, 21, 22, 23, 24, 25, 26, 27])
three = ([ 0, 1, 2, 3, 4, 5, 6, 7])

#Combining the 3 above arrays
conArray = np.concatenate((one,two,three), axis=0)
print(conArray)

#Sorted combined array
comboArray = np.sort(conArray)
print(comboArray)


[10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27  0  1  2  3  4  5  6  7]
[ 0  1  2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]


In [51]:
#Coding Exercise
#Question 14


#print sec1 - the 2nd element
print(comboArray[1])

#print sec2 - all elements from the 3rd element to the last
print(comboArray[2:])

#print sec3 - all elements from the 4th to the 14th elements
print(comboArray[3:15])

#print sec4 - the last 6 elements
print(comboArray[-6:])

#print sec5 - all element from #0 up to and including #15, using the negative number method, i.e. taking a section from the end.
print(comboArray[-24:-10])

#print sec6 - from #20 every even element to the end
print(comboArray[16::2])

#print sec7 - from the last element moving forward, every 5th element.
print(comboArray[25::5]) #Not clear if moving foward is toward 0...


1
[ 2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]
[ 3  4  5  6  7 10 11 12 13 14 15 16]
[22 23 24 25 26 27]
[ 0  1  2  3  4  5  6  7 10 11 12 13 14 15]
[20 22 24 26]
[]


In [12]:
#Coding Exercise
#Question 15

import pandas as pd

#used series
ingredients = pd.Series(["FLour","Milk","Eggs","Spam"], name='Ingredients')
quantity = pd.Series([4, 1, 2, 1], name='Quanitity')
unit = pd.Series(["cups", "cup", "large", "can"], name='Unit')

#print(ingredients)
#print(quantity)
#print(unit)

#created DataFrame
df = pd.DataFrame(ingredients).join(quantity).join(unit)
print(df,"\n Name: Dinner, dtype:object")




  Ingredients  Quanitity   Unit
0       FLour          4   cups
1        Milk          1    cup
2        Eggs          2  large
3        Spam          1    can 
 Name: Dinner, dtype:object


In [13]:
#Coding Exercise
#Question 16
import pandas as pd

#data
info = {
    'Name': ['Jai', 'janusha', 'Gaurav', 'Anuj'],
        'Height': [5.1, 6.2, 5.1, 5.2],
        'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
        'address': ['Delhi', 'Doha', 'Chennai', 'Dakhar'],
        'Age': [21, 23, 24, 21],
        'Pets': ['Dog', 'Bunny', 'Chinchilla', 'Parrot'],
        'sport': ['Darts', 'Basketball', 'PaddleBoarding', 'Cricket']
    }

#created DataFrame
studentData = pd.DataFrame(info)
print("Students Data \n", studentData)

Students Data 
       Name  Height Qualification  address  Age        Pets           sport
0      Jai     5.1           Msc    Delhi   21         Dog           Darts
1  janusha     6.2            MA     Doha   23       Bunny      Basketball
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket


In [14]:
#Coding Exercise
#Question 17

#new column
deserts = pd.Series(["ice cream", "Cashew Fudge", "waffels", "Carrot Halwa"], name='Deserts')

#new column added to DataFrame
studentData_update = pd.DataFrame(studentData).join(deserts)

print(studentData_update)

      Name  Height Qualification  address  Age        Pets           sport  \
0      Jai     5.1           Msc    Delhi   21         Dog           Darts   
1  janusha     6.2            MA     Doha   23       Bunny      Basketball   
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding   
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket   

        Deserts  
0     ice cream  
1  Cashew Fudge  
2       waffels  
3  Carrot Halwa  


In [17]:
#Coding Exercise
#Question 18

#sort by colmn Name
studentData_update.sort_values(by = ['Name'], inplace=True)
print(studentData_update)

#sort by column address
studentData_update.sort_values(by = ['address'], inplace=True)
print(studentData_update)




      Name  Height Qualification  address  Age        Pets           sport  \
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket   
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding   
0      Jai     5.1           Msc    Delhi   21         Dog           Darts   
1  janusha     6.2            MA     Doha   23       Bunny      Basketball   

        Deserts  
3  Carrot Halwa  
2       waffels  
0     ice cream  
1  Cashew Fudge  
      Name  Height Qualification  address  Age        Pets           sport  \
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding   
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket   
0      Jai     5.1           Msc    Delhi   21         Dog           Darts   
1  janusha     6.2            MA     Doha   23       Bunny      Basketball   

        Deserts  
2       waffels  
3  Carrot Halwa  
0     ice cream  
1  Cashew Fudge  


In [21]:
#Coding Exercise
#Question 19

import pandas as pd

#saved DataFrame with specified name
csv = pd.read_csv('/Users/calamese3/code/SavvyCoders/Homework/cows_and_goats.csv')
print(csv)

Empty DataFrame
Columns: [df = pd.DataFrame({'Cows': [12, 20], 'Goats': [22, 19]}, index=['Year 1', 'Year 2']), Unnamed: 1, Unnamed: 2, Unnamed: 3, Unnamed: 4, Unnamed: 5, Unnamed: 6, Unnamed: 7, Unnamed: 8, Unnamed: 9, Unnamed: 10]
Index: []


In [40]:
#Coding Exercise
#Question 20

#Using Pandas, make your own .CSV file with data on vegetables and save it. 
import pandas as pd

#Created .csv file
veg = pd.DataFrame([["Spinach", "Leafy Green"], ["Cabbage", "Cruciferous" ], ["Squash", "Marrow"]], 
                   columns=["Vegetables", "Vegetable Type"])
veg

#Saved created .csv file
veg.to_csv('vegetable_data.csv')

#veg = pd.read_csv('vegetable_data.csv')
#print(veg)




In [42]:
#Coding Exercise
#Question 20
#Using Pandas, make a change to your CSV file, and save a copy with a different name.

#change to .csv file using Pandas and saved copy with new name.
veg.to_csv('vegetable_update.csv', index=False)
veg = pd.read_csv('vegetable_update.csv') 


print(veg)


  Vegetables Vegetable Type
0    Spinach    Leafy Green
1    Cabbage    Cruciferous
2     Squash         Marrow
